#server:
#  port: 8088
#  spring:
#    application:
#      name: CONFIG-SERVER
#    cloud:
#      config:
#        server:
#          uri: https://github.com/ArunKr032Singh/micro-service-config
#          clone-on-start: true
#
